# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: run
  run:
    cmds:
      - cargo run {{ .CLI_ARGS }}
  test:
    cmds:
      - cargo test
  lint:
    cmds:
      - cargo clippy
